#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                     - R^3 Figure 8 Challenge -
|*																				Edited by Eric Lind																					*|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to make a combination of point turns and driving straight				*|
|*  to complete a figure 8 around two obstacles. The implementation uses funtions for driving and			*|
|*  turning to clean up 'main', and allow for the logic to be more clear. 														*|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*    3)  Point Turns, or turns in place, are achieved by having the motors spin in opposite          *|
|*        directions, at the same value for speed.                             												*|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
void a (int x){ //drive function. passed value is duration of movement
	wait1Msec(1000); 			//remove later, for testing purposes
	motor[rightMotor] = 127;		  // Motor on port2 is run at full (-127) power reverse
	motor[leftMotor]  = 127;
	wait1Msec(x);										//how long the motors run
	motor[leftMotor]=0;							//stop motors after desired movement is completed
	motor[rightMotor]=0;
}
void b (bool isright, int del){				//turn fnction. passed values are a boolean true/false to turn right or left, and duration of turn
	wait1Msec(1000); //remove later
	if(isright){    										//passed boolean decides if turn is right or left. a false value makes the robot turn left.
		motor[rightMotor] = -127;		  // Motor on port2 is run at full (-127) power reverse
		motor[leftMotor]  = 127;
		wait1Msec(del);	     					//how long the motors run
		motor[leftMotor]=0;							//stop motors after desired movement is completed
			motor[rightMotor]=0;
	}
	else {
		// Turn Left at full power for 0.75 seconds
	motor[rightMotor] = 127;			// Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = -127;		  // Motor on port3 is run at full (-127) power reverse
	wait1Msec(750);								//how long the motors run
		motor[leftMotor]=0;					//stop motors after desired movement is completed
		motor[rightMotor]=0;
	}
}

task main()
{
	wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program


	//complete figure 8. after each function call, the program waits for the function to complete before moving onto the next step.
	a(750);
	b(false, 750);
	a(750);
	b(false, 360);
	a(750);
	b(true, 1000);
	a(750);
	b(true, 1000);
	a(750);
	b(false, 360);
	a(750);



}													      // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
